<!doctype html>
<html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"><meta><title>错误、调试与测试 - MCFON</title><link rel="manifest" href="/manifest.json"><meta name="application-name" content="MCFON"><meta name="msapplication-TileImage" content="/img/favicon.png"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="MCFON"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="description" content="简述 在程序运行过程中我们总会遇到各种各样的错误。有的错误是程序编写有问题造成的，比如本来应该输出整数结果输出了字符串，这种错误我们通常称之为bug，bug是必须修复的；有的错误是用户输入造成的，比如让用户输入email地址，结果得到一个空字符串，这种错误可以通过检查用户输入来做相应的处理；还有一类错误是完全无法预测的，比如写入文件的时候，磁盘满了，写不进去了，或者从网络抓取数据，网络突然断掉了。"><meta property="og:type" content="blog"><meta property="og:title" content="错误、调试与测试"><meta property="og:url" content="https://hunlp.com/posts/38807.html"><meta property="og:site_name" content="MCFON"><meta property="og:description" content="简述 在程序运行过程中我们总会遇到各种各样的错误。有的错误是程序编写有问题造成的，比如本来应该输出整数结果输出了字符串，这种错误我们通常称之为bug，bug是必须修复的；有的错误是用户输入造成的，比如让用户输入email地址，结果得到一个空字符串，这种错误可以通过检查用户输入来做相应的处理；还有一类错误是完全无法预测的，比如写入文件的时候，磁盘满了，写不进去了，或者从网络抓取数据，网络突然断掉了。"><meta property="og:locale" content="zh_CN"><meta property="og:image" content="https://hunlp.com/img/og_image.png"><meta property="article:published_time" content="2017-06-22T17:35:34.000Z"><meta property="article:modified_time" content="2021-06-08T12:38:05.025Z"><meta property="article:author" content="ฅ´ω`ฅ"><meta property="article:tag" content="笔记"><meta property="twitter:card" content="summary"><meta property="twitter:image" content="/img/og_image.png"><script type="application/ld+json">{"@context":"https://schema.org","@type":"BlogPosting","mainEntityOfPage":{"@type":"WebPage","@id":"https://hunlp.com/posts/38807.html"},"headline":"错误、调试与测试","image":["https://hunlp.com/img/og_image.png"],"datePublished":"2017-06-22T17:35:34.000Z","dateModified":"2021-06-08T12:38:05.025Z","author":{"@type":"Person","name":"ฅ´ω`ฅ"},"publisher":{"@type":"Organization","name":"MCFON","logo":{"@type":"ImageObject","url":"https://hunlp.com/img/logo.png"}},"description":"简述 在程序运行过程中我们总会遇到各种各样的错误。有的错误是程序编写有问题造成的，比如本来应该输出整数结果输出了字符串，这种错误我们通常称之为bug，bug是必须修复的；有的错误是用户输入造成的，比如让用户输入email地址，结果得到一个空字符串，这种错误可以通过检查用户输入来做相应的处理；还有一类错误是完全无法预测的，比如写入文件的时候，磁盘满了，写不进去了，或者从网络抓取数据，网络突然断掉了。"}</script><link rel="canonical" href="https://hunlp.com/posts/38807.html"><link rel="icon" href="/img/favicon.png"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@9.12.0/styles/atom-one-light.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;600&amp;family=Source+Code+Pro"><link rel="stylesheet" href="/css/default.css"><style>body>.footer,body>.navbar,body>.section{opacity:0}</style><!--!--><script>var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "//hm.baidu.com/hm.js?b99420d7a06d2b3361a8efeaf6e20764";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();</script><!--!--><!--!--><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lightgallery@1.10.0/dist/css/lightgallery.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css"><script src="https://www.googletagmanager.com/gtag/js?id=UA-131608076-1" async></script><script>window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
    
        gtag('config', 'UA-131608076-1');</script><!--!--><!--!--><!--!--><style>.pace{-webkit-pointer-events:none;pointer-events:none;-webkit-user-select:none;-moz-user-select:none;user-select:none}.pace-inactive{display:none}.pace .pace-progress{background:#3273dc;position:fixed;z-index:2000;top:0;right:100%;width:100%;height:2px}</style><script src="https://cdn.jsdelivr.net/npm/pace-js@1.2.4/pace.min.js"></script><!--!--><!--!--><!-- hexo injector head_end start --><script>
  (function () {
      function switchTab() {
          if (!location.hash) {
            return;
          }
          Array
              .from(document.querySelectorAll('.tab-content'))
              .forEach($tab => {
                  $tab.classList.add('is-hidden');
              });
          Array
              .from(document.querySelectorAll('.tabs li'))
              .forEach($tab => {
                  $tab.classList.remove('is-active');
              });
          const $activeTab = document.querySelector(location.hash);
          if ($activeTab) {
              $activeTab.classList.remove('is-hidden');
          }
          const $tabMenu = document.querySelector(`a[href="${location.hash}"]`);
          if ($tabMenu) {
              $tabMenu.parentElement.classList.add('is-active');
          }
      }
      switchTab();
      window.addEventListener('hashchange', switchTab, false);
  })();
  </script><!-- hexo injector head_end end --><meta name="generator" content="Hexo 6.1.0"></head><body class="is-3-column"><nav class="navbar navbar-main"><div class="container navbar-container"><div class="navbar-brand justify-content-center"><a class="navbar-item navbar-logo" href="/"><img src="/img/logo.png" alt="MCFON" height="28"></a></div><div class="navbar-menu"><div class="navbar-start"><a class="navbar-item" href="/">主页</a><a class="navbar-item" href="/archives">归档</a><a class="navbar-item" href="/categories">分类</a><a class="navbar-item" href="/tags">标签</a><a class="navbar-item" href="/about">关于</a><a class="navbar-item" href="/friend">友链</a></div><div class="navbar-end"><a class="navbar-item" target="_blank" rel="noopener" title="Download on GitHub" href="https://github.com/ppoffice/hexo-theme-icarus"><i class="fab fa-github"></i></a><a class="navbar-item is-hidden-tablet catalogue" title="目录" href="javascript:;"><i class="fas fa-list-ul"></i></a><a class="navbar-item search" title="搜索" href="javascript:;"><i class="fas fa-search"></i></a></div></div></div></nav><section class="section"><div class="container"><div class="columns"><div class="column order-2 column-main is-8-tablet is-8-desktop is-9-widescreen"><div class="card"><article class="card-content article" role="article"><h1 class="title is-size-3 is-size-4-mobile has-text-weight-normal"><i class="fas fa-angle-double-right"></i>错误、调试与测试</h1><div class="article-meta is-size-7 is-uppercase level is-mobile"><div class="level-left"><span class="level-item"><i class="far fa-calendar-alt"> </i><time dateTime="${date_xml(page.date)}" title="${date_xml(page.date)}">2017-06-23</time></span><span class="level-item is-hidden-mobile"><i class="far fa-calendar-check"> </i><time dateTime="${date_xml(page.updated)}" title="${date_xml(page.updated)}">2021-06-08</time></span><span class="level-item"><a class="link-muted" href="/categories/Python/">Python</a></span><span class="level-item">1 小时读完 (大约9591个字)</span></div></div><div class="content"><h2 id="简述">简述</h2>
<p>在程序运行过程中我们总会遇到各种各样的<strong>错误</strong>。有的错误是程序编写有问题造成的，比如本来应该输出整数结果输出了字符串，这种错误我们通常称之为<strong>bug</strong>，bug是必须修复的；有的错误是用户输入造成的，比如让用户输入email地址，结果得到一个空字符串，这种错误可以通过检查用户输入来做相应的处理；还有一类错误是完全无法预测的，比如写入文件的时候，磁盘满了，写不进去了，或者从网络抓取数据，网络突然断掉了。这类错误也称为<strong>异常</strong>，在程序中通常是必须处理的，否则，程序会因为各种问题终止并退出。Python内置了一套异常处理机制，可以帮助我们处理这些错误。 <span id="more"></span> 此外，在编写代码时，我们可能会需要跟踪程序的执行，查看变量的值是否正确，然后再进行调整或者下一步操作，这个过程称为<strong>调试</strong>。Python的<strong>pdb</strong>可以让我们以<strong>单步方式</strong>执行代码，从而方便地调试程序。</p>
<p>最后，编写<strong>测试</strong>也很重要。编写好测试文件，这样当我们改动了代码或者实现了新的功能时，只需再运行一遍测试，就能知道原来的功能有没有出错，程序是否依然能输出我们期望的结果了。</p>
<hr />
<p><br></p>
<h2 id="错误处理">错误处理</h2>
<h3 id="错误码">错误码</h3>
<p>在程序运行的过程中，如果发生了错误，可以<strong>返回一个事先约定的错误代码</strong>，这样，就可以知道是否有错，以及出错的原因。在操作系统提供的调用中，返回错误码非常常见。比如打开文件的函数 <code>open()</code>，成功时返回文件描述符（就是一个整数），出错时返回-1。</p>
<p>用错误码来表示是否出错十分不便，因为<strong>函数本身既可能返回正常结果又可能返回错误码</strong>，所以调用者不得不用大量的代码来判断属于哪一种情况。例如：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">def</span> <span class="title function_">foo</span>():</span><br><span class="line">    r = some_function()</span><br><span class="line">    <span class="keyword">if</span> r==(-<span class="number">1</span>):</span><br><span class="line">        <span class="keyword">return</span> (-<span class="number">1</span>)</span><br><span class="line">    <span class="comment"># do something</span></span><br><span class="line">    <span class="keyword">return</span> r</span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">bar</span>():</span><br><span class="line">    r = foo()</span><br><span class="line">    <span class="keyword">if</span> r==(-<span class="number">1</span>):</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;Error&#x27;</span>)</span><br><span class="line">    <span class="keyword">else</span>:</span><br><span class="line">        <span class="keyword">pass</span></span><br></pre></td></tr></table></figure>
<p>函数 <code>foo</code> 既可能返回正常结果又可能返回错误码，因此调用 <code>foo</code> 的函数 <code>bar</code> 就不得不先进行判断，检查返回的是正常结果还是错误码。这种情况在有多种错误码时显得更为麻烦。</p>
<p>还有一个很大的缺点是，使用错误码时，一旦出错，就必须把这个错误码一级一级上报，直到某个函数可以处理该错误（比如，给用户输出一个错误信息）。假如上面例子中 <code>bar</code> 函数无法处理错误，就必须继续返回错误码给调用 <code>bar</code> 的上级函数，以此类推。并且在返回的过程中，我们在每个中间函数中都要对错误码进行判断，这样写出来的程序有“半壁江山”都被处理错误的逻辑占据了，着实可怕。。。</p>
<p>有没有可以替代错误码又能处理错误的方案呢？有的！基本上，所有高级语言都内置了一套 <code>try...except...finally...</code> 的错误处理机制，Python也不例外，在下一小节中将介绍这种错误处理机制。</p>
<hr />
<h3 id="try...except...finally">try...except...finally</h3>
<p><code>try...except...finally...</code> 机制的工作方式是这样的：</p>
<ul>
<li>当我们认为某段代码可能会出错时，可以用 <code>try</code> 来运行这段代码，如果运行出错，则这段代码会<strong>终止在错误出现的地方</strong>；</li>
<li>如果后续代码中 <code>except</code> 语句成功捕获到错误，程序就会执行 <code>except</code> 语句块内的代码处理错误。如果没有捕获到，则错误没有得到处理，程序就会停止运行；</li>
<li>最后，<strong>无论是否出错，无论是否成功捕获到错误</strong>，<code>finally</code> 语句块内的代码都会被执行。</li>
</ul>
<p><code>try...except...finally...</code> 机制中，我们<strong>可以不使用 <code>finally</code> 语句块，但 <code>try</code> 和 <code>except</code> 是一定要同时出现的</strong>，<code>except</code> 不一定能成功捕获 <code>try</code> 语句块内的错误，如果捕获不成功，程序就会终止运行。</p>
<p>接下来看一个使用 <code>try...except...finally...</code> 机制处理错误的具体案例：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;try...&#x27;</span>)</span><br><span class="line">    r = <span class="number">10</span> / <span class="number">0</span></span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;result:&#x27;</span>, r)</span><br><span class="line"><span class="keyword">except</span> ZeroDivisionError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;except:&#x27;</span>, e)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;finally...&#x27;</span>)</span><br><span class="line"><span class="built_in">print</span>(<span class="string">&#x27;END&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>上面的代码在计算 <code>10 / 0</code> 时会产生一个除零错误，得到输出：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>...</span><br><span class="line"><span class="keyword">except</span>: division by zero</span><br><span class="line"><span class="keyword">finally</span>...</span><br><span class="line">END</span><br></pre></td></tr></table></figure>
<p>从输出可以看到，当错误发生时，后续语句 <code>print('result:', r)</code> 不会被执行，由于 <code>except</code> 语句捕获到这个 <code>ZeroDivisionError</code> 错误，因此 <code>except</code> 语句块里的代码会被执行。最后，<code>finally</code> 语句块里的代码也会被执行。<strong>又因为错误得到了处理，所以之后程序会继续运行后续代码，输出 <code>END</code></strong>。</p>
<p>如果把除数0改成2，则执行结果如下：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>...</span><br><span class="line">result: <span class="number">5</span></span><br><span class="line"><span class="keyword">finally</span>...</span><br><span class="line">END</span><br></pre></td></tr></table></figure>
<p>由于<strong>没有错误发生</strong>，所以 <strong><code>except</code> 语句块不会被执行</strong>，但是 <code>finally</code> 语句块只要存在，就一定会被执行。</p>
<p>除了上面出现的 <code>ZeroDivisionError</code> 错误，在实际运行中，还有可能出现各种不同类型的错误。<strong>不同类型的错误应该由不同的 <code>except</code> 语句块进行处理</strong>。我们可以使用多个 <code>except</code> 语句来捕获不同类型的错误：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;try...&#x27;</span>)</span><br><span class="line">    r = <span class="number">10</span> / <span class="built_in">int</span>(<span class="string">&#x27;a&#x27;</span>)</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;result:&#x27;</span>, r)</span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;ValueError:&#x27;</span>, e)</span><br><span class="line"><span class="keyword">except</span> ZeroDivisionError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;ZeroDivisionError:&#x27;</span>, e)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;finally...&#x27;</span>)</span><br><span class="line"><span class="built_in">print</span>(<span class="string">&#x27;END&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>因为当 <code>int()</code> 函数无法把参数转换为 <code>int</code> 类型时会抛出 <code>ValueError</code> 错误，我们用一个 <code>except</code> 来捕获和处理 <code>ValueError</code>，用另一个 <code>except</code> 来捕获并处理做除法可能产生的 <code>ZeroDivisionError</code>。</p>
<p>特别地，我们还<strong>可以在 <code>except</code> 语句块后面加一个 <code>else</code> 语句块</strong>。当错误没有发生时，就会执行 <code>else</code> 语句内的代码：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;try...&#x27;</span>)</span><br><span class="line">    r = <span class="number">10</span> / <span class="built_in">int</span>(<span class="string">&#x27;2&#x27;</span>)</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;result:&#x27;</span>, r)</span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;ValueError:&#x27;</span>, e)</span><br><span class="line"><span class="keyword">except</span> ZeroDivisionError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;ZeroDivisionError:&#x27;</span>, e)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;no error!&#x27;</span>)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;finally...&#x27;</span>)</span><br><span class="line"><span class="built_in">print</span>(<span class="string">&#x27;END&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>我们常说，在Python中一切皆对象。其实呀，Python中的错误也是采用面向对象实现的，<strong>每一种错误都是一个类，<code>BaseException</code> 类是所有错误类型最顶级的父类</strong>。在使用 <code>except</code> 时需要注意，它<strong>不但会捕获所指定类型的错误，还把属于该类型子类的错误一并捕获</strong>。比如：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    foo()</span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;ValueError&#x27;</span>)</span><br><span class="line"><span class="keyword">except</span> UnicodeError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;UnicodeError&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>这里的第二个 <code>except</code> 永远也不会捕获到 <code>UnicodeError</code>，因为 <code>UnicodeError</code> 是 <code>ValueError</code> 的子类，如果出现了 <code>UnicodeError</code> 就一定会被第一个 <code>except</code> 语句捕获。</p>
<p>常见的错误类型和继承关系看这里：</p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy">https://docs.python.org/3/library/exceptions.html#exception-hierarchy</a></p>
<p>在上一小节中，我们说到了使用错误码处理错误有两大缺点，一是<strong>函数既可能返回正常结果也可能返回错误码</strong>，二是<strong>一旦发生错误必须层层上报</strong>。那么使用 <code>try...except...finally...</code> 机制是否能克服这两个缺点呢？答案是肯定的！举个例子：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">def</span> <span class="title function_">foo</span>(<span class="params">s</span>):</span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / <span class="built_in">int</span>(s)</span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">bar</span>(<span class="params">s</span>):</span><br><span class="line">    <span class="keyword">return</span> foo(s) * <span class="number">2</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">main</span>():</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        bar(<span class="string">&#x27;0&#x27;</span>)</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;Error:&#x27;</span>, e)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;finally...&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>这里我们在 <code>main</code> 函数中调用 <code>bar</code> 函数，在 <code>bar</code> 函数中调用 <code>foo</code> 函数。我们使用 <code>try</code> 模块来运行调用代码，当 <code>foo</code> 函数发生错误时，我们不需要返回错误码，也不需要一级级上报，程序会自动寻找对应的 <code>except</code> 语句进行错误处理。也即是说，<strong>不需要在每个可能出错的地方去捕获错误，只要在合适的层次去捕获错误就可以了</strong>。这样一来，我们就能使用非常简洁的方式来处理程序运行中可能出现的错误了。</p>
<hr />
<h3 id="错误的调用链">错误的调用链</h3>
<p>如果错误没有被捕获，就会一直往上抛，最后<strong>被Python解释器捕获</strong>，打印出错误信息，然后程序终止运行。</p>
<p>编写一个包含如下代码的 <code>err.py</code> 文件：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># err.py:</span></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">foo</span>(<span class="params">s</span>):</span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / <span class="built_in">int</span>(s)</span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">bar</span>(<span class="params">s</span>):</span><br><span class="line">    <span class="keyword">return</span> foo(s) * <span class="number">2</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">main</span>():</span><br><span class="line">    bar(<span class="string">&#x27;0&#x27;</span>)</span><br><span class="line"></span><br><span class="line">main()</span><br></pre></td></tr></table></figure>
<p>执行该文件，结果如下：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">$ python3 err.py</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">&quot;err.py&quot;</span>, line <span class="number">11</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    main()</span><br><span class="line">  File <span class="string">&quot;err.py&quot;</span>, line <span class="number">9</span>, <span class="keyword">in</span> main</span><br><span class="line">    bar(<span class="string">&#x27;0&#x27;</span>)</span><br><span class="line">  File <span class="string">&quot;err.py&quot;</span>, line <span class="number">6</span>, <span class="keyword">in</span> bar</span><br><span class="line">    <span class="keyword">return</span> foo(s) * <span class="number">2</span></span><br><span class="line">  File <span class="string">&quot;err.py&quot;</span>, line <span class="number">3</span>, <span class="keyword">in</span> foo</span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / <span class="built_in">int</span>(s)</span><br><span class="line">ZeroDivisionError: division by zero</span><br></pre></td></tr></table></figure>
<p>出错并不可怕，可怕的是不知道哪里出错了。解读错误信息是定位错误的关键。我们<strong>从上往下可以看到整个错误的函数调用链</strong>：</p>
<p>错误信息的第1行：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br></pre></td></tr></table></figure>
<p>这句话告诉我们下面是错误的跟踪信息。</p>
<p>错误信息的第2~3行：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">File <span class="string">&quot;err.py&quot;</span>, line <span class="number">11</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">  main()</span><br></pre></td></tr></table></figure>
<p>告诉我们调用 <code>main()</code> 出错了，具体是在代码文件 <code>err.py</code> 的第11行代码。</p>
<p>错误信息的第4~5行：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">File <span class="string">&quot;err.py&quot;</span>, line <span class="number">9</span>, <span class="keyword">in</span> main</span><br><span class="line">  bar(<span class="string">&#x27;0&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>告诉我们调用 <code>bar('0')</code> 出错了，具体是在代码文件 <code>err.py</code> 的第9行代码。</p>
<p>错误信息的第6~7行：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">File <span class="string">&quot;err.py&quot;</span>, line <span class="number">6</span>, <span class="keyword">in</span> bar</span><br><span class="line">  <span class="keyword">return</span> foo(s) * <span class="number">2</span></span><br></pre></td></tr></table></figure>
<p>告诉我们调用 <code>foo(s)</code> 出错了，具体是在代码文件 <code>err.py</code> 的第6行代码。</p>
<p>错误信息的第8~9行：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">File <span class="string">&quot;err.py&quot;</span>, line <span class="number">3</span>, <span class="keyword">in</span> foo</span><br><span class="line">  <span class="keyword">return</span> <span class="number">10</span> / <span class="built_in">int</span>(s)</span><br></pre></td></tr></table></figure>
<p>告诉我们语句 <code>return 10 / int(s)</code> 出错了，具体是在代码文件 <code>err.py</code> 的第3行代码。这是错误的源头，因为下面打印了具体的错误原因：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">ZeroDivisionError: integer division <span class="keyword">or</span> modulo by zero</span><br></pre></td></tr></table></figure>
<p>根据错误类型 <code>ZeroDivisionError</code>，我们可以判断 <code>int(s)</code> 本身并没有出错，但是 <code>int(s)</code>返回了0，在计算 <code>10 / 0</code> 时程序出错了。这和我们使用 <code>except</code> 来捕获错误信息时打印出的内容是一样的。</p>
<hr />
<h3 id="记录错误">记录错误</h3>
<p>上一小节讲到，如果不在代码中进行错误处理，Python解释器最终会捕获错误并打印出错误调用链，但同时程序也会终止运行。那么，有没有<strong>既能打印出错误调用链，帮助我们分析出错的原因和源头，同时又能让程序继续运行</strong>的方法呢？有的，Python内置的 <code>logging</code> 模块可以帮助我们非常容易地记录错误信息。</p>
<p>这里举一个简单的例子，首先编写 <code>err_logging.py</code> 文件：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> logging</span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">foo</span>(<span class="params">s</span>):</span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / <span class="built_in">int</span>(s)</span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">bar</span>(<span class="params">s</span>):</span><br><span class="line">    <span class="keyword">return</span> foo(s) * <span class="number">2</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">main</span>():</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        bar(<span class="string">&#x27;0&#x27;</span>)</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        logging.exception(e) <span class="comment"># 使用logging模块的exception方法打印错误信息</span></span><br><span class="line"></span><br><span class="line">main()</span><br><span class="line"><span class="built_in">print</span>(<span class="string">&#x27;END&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>同样是打印出错误调用链，但程序打印完错误信息后会继续运行，并正常结束：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">$ python3 err_logging.py</span><br><span class="line">ERROR:root:division by zero</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">&quot;err_logging.py&quot;</span>, line <span class="number">13</span>, <span class="keyword">in</span> main</span><br><span class="line">    bar(<span class="string">&#x27;0&#x27;</span>)</span><br><span class="line">  File <span class="string">&quot;err_logging.py&quot;</span>, line <span class="number">9</span>, <span class="keyword">in</span> bar</span><br><span class="line">    <span class="keyword">return</span> foo(s) * <span class="number">2</span></span><br><span class="line">  File <span class="string">&quot;err_logging.py&quot;</span>, line <span class="number">6</span>, <span class="keyword">in</span> foo</span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / <span class="built_in">int</span>(s)</span><br><span class="line">ZeroDivisionError: division by zero</span><br><span class="line">END</span><br></pre></td></tr></table></figure>
<p>此外，我们还可以借助 <code>logging</code> 模块把错误信息记录到日志文件里，方便事后排查，这里不作举例了。</p>
<hr />
<h3 id="抛出错误">抛出错误</h3>
<p>前面我们说到，在Python中错误都是通过类来实现的，捕获一个错误就是捕获到该类的一个实例。<strong>错误并不是凭空产生的，而是有意地创建并抛出的</strong>。Python的内置函数会抛出很多不同类型的错误，我们自己编写函数时也可以这样做。</p>
<p>举一个简单的例子，首先编写 <code>err_raise.py</code> 文件：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">class</span> <span class="title class_">FooError</span>(<span class="title class_ inherited__">ValueError</span>):</span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">foo</span>(<span class="params">s</span>):</span><br><span class="line">    n = <span class="built_in">int</span>(s)</span><br><span class="line">    <span class="keyword">if</span> n==<span class="number">0</span>:</span><br><span class="line">        <span class="keyword">raise</span> FooError(<span class="string">&#x27;invalid value: %s&#x27;</span> % s)</span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / n</span><br><span class="line"></span><br><span class="line">foo(<span class="string">&#x27;0&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>这里我们自定义了一个错误类型 <code>FooError</code>，继承自 <code>ValueError</code>。<strong>使用 <code>raise</code> 语句抛出一个错误的实例</strong>。执行 <code>err_raise.py</code>，最终可以跟踪到我们自定义的错误类型：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">$ python3 err_raise.py</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">&quot;err_throw.py&quot;</span>, line <span class="number">11</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    foo(<span class="string">&#x27;0&#x27;</span>)</span><br><span class="line">  File <span class="string">&quot;err_throw.py&quot;</span>, line <span class="number">8</span>, <span class="keyword">in</span> foo</span><br><span class="line">    <span class="keyword">raise</span> FooError(<span class="string">&#x27;invalid value: %s&#x27;</span> % s)</span><br><span class="line">__main__.FooError: invalid value: <span class="number">0</span></span><br></pre></td></tr></table></figure>
<p><strong>只有在必要的时候才自定义错误类型</strong>。如果可以使用Python内置的错误类型（比如ValueError，TypeError等等），就应尽量使用Python内置的错误类型。</p>
<p>最后，我们来看另一种错误处理的方式，首先编写 <code>err_reraise.py</code> 文件：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">def</span> <span class="title function_">foo</span>(<span class="params">s</span>):</span><br><span class="line">    n = <span class="built_in">int</span>(s)</span><br><span class="line">    <span class="keyword">if</span> n==<span class="number">0</span>:</span><br><span class="line">        <span class="keyword">raise</span> ValueError(<span class="string">&#x27;invalid value: %s&#x27;</span> % s)</span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / n</span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">bar</span>():</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        foo(<span class="string">&#x27;0&#x27;</span>)</span><br><span class="line">    <span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;ValueError!&#x27;</span>)</span><br><span class="line">        <span class="keyword">raise</span></span><br><span class="line"></span><br><span class="line">bar()</span><br></pre></td></tr></table></figure>
<p>在 <code>bar()</code> 函数中，我们明明已经捕获了错误，但是，打印一个 <code>ValueError</code> 之后，又把错误通过 <code>raise</code> 语句再次抛出去了，为什么呢？</p>
<p>其实这种错误处理方式并没有错，而且相当常见。有时候，捕获错误的目的只是记录一下，便于后续追踪。如果当前函数没有处理该错误的逻辑，最恰当的方式就是继续往上抛，让顶层调用者去处理。好比一个员工处理不了一个问题时，就把问题抛给他的老板，如果他的老板也处理不了，就一直往上抛，最终抛给CEO去处理。</p>
<p>特别地，当 <code>raise</code> 语句不带参数时，会把当前错误原样抛出。但既然我们可以在 <code>except</code> 语句块中使用 <code>raise</code> 语句，那就可以轻易地抛出一个别的错误，从而<strong>把一种错误类型转换成另一种错误类型</strong>。例如：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">10</span> / <span class="number">0</span></span><br><span class="line"><span class="keyword">except</span> ZeroDivisionError:</span><br><span class="line">    <span class="keyword">raise</span> ValueError(<span class="string">&#x27;input error!&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>当然，我们不能滥用这样的功能，只有在有必要进行转换时才进行合理的转换。</p>
<hr />
<h3 id="小结">小结</h3>
<p>使用Python内置的 <code>try...except...finally</code> 机制可以十分方便地处理错误。但出错时，会分析错误信息并定位错误发生的位置才是最关键的。</p>
<p>我们编写模块时可以在代码中主动抛出错误，让调用者来处理相应的错误。但是，我们应当在模块的文档中写清楚可能会抛出哪些错误，以及错误产生的原因。</p>
<hr />
<p><br></p>
<h2 id="调试">调试</h2>
<p>程序运行总会有各种各样的bug，有的bug很简单，看看错误信息就知道；但有的bug很复杂，我们不但需要知道错误类型和出错的地方，还需要知道一些变量的值才能做出准确的推断。<strong>跟踪程序的执行，查看变量的值</strong>这个过程就称为调试，这一节会介绍各种调试程序的手段。</p>
<h3 id="直接打印">直接打印</h3>
<p>直接打印是一种直接粗暴但十分有效的方法，简单来说就是使用 <code>print()</code> 把可能有问题的变量打印出来看看：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">def</span> <span class="title function_">foo</span>(<span class="params">s</span>):</span><br><span class="line">    n = <span class="built_in">int</span>(s)</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;n = %d&#x27;</span> % n)</span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / n</span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">main</span>():</span><br><span class="line">    foo(<span class="string">&#x27;0&#x27;</span>)</span><br><span class="line"></span><br><span class="line">main()</span><br></pre></td></tr></table></figure>
<p>执行后在输出中查找打印的变量值：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">$ python3 err.py</span><br><span class="line">n = <span class="number">0</span></span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  ...</span><br><span class="line">ZeroDivisionError: integer division <span class="keyword">or</span> modulo by zero</span><br></pre></td></tr></table></figure>
<p>这样我们就知道除零错误是因为变量 <code>n</code> 的值不合理而产生的了。</p>
<p>但是使用直接打印来调试有一个很大的缺点，在完成调试后，我们还得删掉代码里用于输出变量值的 <code>pinrt()</code>，如果我们要观察很多变量的值，那么代码里就会到处都是 <code>print()</code>，运行结果也会包含很多垃圾信息，删除的时候就会很麻烦。</p>
<hr />
<h3 id="断言">断言</h3>
<p>我们可以用<strong>断言（assert）</strong>来替代 <code>print()</code>，例如：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">def</span> <span class="title function_">foo</span>(<span class="params">s</span>):</span><br><span class="line">    n = <span class="built_in">int</span>(s)</span><br><span class="line">    <span class="keyword">assert</span> n != <span class="number">0</span>, <span class="string">&#x27;n is zero!&#x27;</span></span><br><span class="line">    <span class="keyword">return</span> <span class="number">10</span> / n</span><br><span class="line"></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">main</span>():</span><br><span class="line">    foo(<span class="string">&#x27;0&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>我们看到，使用 <code>assert</code> 的方法是在它后面接一个表达式以及一个字符串，如果表达式不为 <code>True</code>，则断言失败，此时会抛出 <code>AssertionError</code> 错误，并输出自定义的错误信息（跟在表达式后面的字符串）：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">$ python3 err.py</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  ...</span><br><span class="line">AssertionError: n <span class="keyword">is</span> zero!</span><br></pre></td></tr></table></figure>
<p>程序中如果到处充斥着 <code>assert</code> 语句，似乎和使用 <code>print()</code> 相比也没有什么不同。但是，我们可以<strong>在启动Python解释器时可以用 <code>-O</code> 参数来关闭 <code>assert</code></strong>：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">$ python3 -O err.py</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  ...</span><br><span class="line">ZeroDivisionError: division by zero</span><br></pre></td></tr></table></figure>
<p>关闭后，可以把所有的 <code>assert</code> 语句当成 <code>pass</code> 来看，此时断言就不会发挥作用了。</p>
<hr />
<h3 id="logging">logging</h3>
<p>我们还可以把 <code>print()</code> 替换为 <code>logging</code>。和 <code>assert</code> 相比，使用 <code>logging</code> 不会抛出错误，而且不但能打印信息还能方便地保存到日志中。这里简单举个例子，首先编写 <code>err.py</code> 文件：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> logging</span><br><span class="line"></span><br><span class="line">s = <span class="string">&#x27;0&#x27;</span></span><br><span class="line">n = <span class="built_in">int</span>(s)</span><br><span class="line">logging.info(<span class="string">&#x27;n = %d&#x27;</span> % n)</span><br><span class="line"><span class="built_in">print</span>(<span class="number">10</span> / n)</span><br></pre></td></tr></table></figure>
<p><code>logging.info()</code> 可以输出一段文本。但运行上述代码，发现除了抛出 <code>ZeroDivisionError</code> 错误之外，没有任何信息。怎么回事呢？</p>
<p>别急，在 <code>import logging</code> 之后添加一行配置再试试：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> logging</span><br><span class="line">logging.basicConfig(level=logging.INFO)</span><br></pre></td></tr></table></figure>
<p>再次运行，此时能看到输出了：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">$ python3 err.py</span><br><span class="line">INFO:root:n = <span class="number">0</span></span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">&quot;err.py&quot;</span>, line <span class="number">8</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    <span class="built_in">print</span>(<span class="number">10</span> / n)</span><br><span class="line">ZeroDivisionError: division by zero</span><br></pre></td></tr></table></figure>
<p>这就是使用 <code>logging</code> 的好处了，它允许开发者<strong>指定记录信息的级别</strong>，按程度由低到高有 <code>debug</code>, <code>info</code>, <code>waring</code>, <code>error</code> 几个级别。当我们指定 <code>level=INFO</code> 时，<code>logging.debug</code> 就不起作用了。同理，指定 <code>level=WARNING</code> 后，<code>debug</code> 和 <code>info</code> 就不起作用了。这样一来，我们可以很方便地统一控制输出哪个级别的信息，而不用担心调试完还要删除的问题了。</p>
<p>使用 <code>logging</code> 还有另一个好处就是可以通过很简单的配置，把一条语句同时输出到不同的地方，比如命令行和文件。</p>
<hr />
<h3 id="pdb">pdb</h3>
<p>前面几种方式都需要插入额外的代码，有没有不需要插入代码的调试方式呢？有的！我们可以启动<strong>Python自带的pdb调试器</strong>，让程序<strong>以单步方式运行</strong>，可以随时查看运行到某一步时各个变量的值。首先编写好 <code>err.py</code> 文件：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># err.py</span></span><br><span class="line">s = <span class="string">&#x27;0&#x27;</span></span><br><span class="line">n = <span class="built_in">int</span>(s)</span><br><span class="line"><span class="built_in">print</span>(<span class="number">10</span> / n)</span><br></pre></td></tr></table></figure>
<p>以参数 <code>-m pdb</code> 来启动pdb调试环境：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python -m pdb err.py</span><br><span class="line">&gt; c:\users\administrator\desktop\err.py(<span class="number">2</span>)&lt;module&gt;()</span><br><span class="line">-&gt; s = <span class="string">&#x27;0&#x27;</span></span><br></pre></td></tr></table></figure>
<p>此时输出有两行，第一行表示下一步执行的代码属于哪一个代码文件的哪一行（这里是 <code>err.py</code> 的第2行）；第二行则是下一步执行的代码。我们可以输入命令 <code>l</code> 来查看这行代码的上下文：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">(Pdb) l</span><br><span class="line">  <span class="number">1</span>     <span class="comment"># err.py</span></span><br><span class="line">  <span class="number">2</span>  -&gt; s = <span class="string">&#x27;0&#x27;</span></span><br><span class="line">  <span class="number">3</span>     n = <span class="built_in">int</span>(s)</span><br><span class="line">  <span class="number">4</span>     <span class="built_in">print</span>(<span class="number">10</span> / n)</span><br><span class="line">[EOF]</span><br></pre></td></tr></table></figure>
<p>输入命令 <code>n</code> 可以单步执行该行代码：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">(Pdb) n</span><br><span class="line">&gt; c:\users\administrator\desktop\err.py(<span class="number">3</span>)&lt;module&gt;()</span><br><span class="line">-&gt; n = <span class="built_in">int</span>(s)</span><br><span class="line">(Pdb) n</span><br><span class="line">&gt; c:\users\administrator\desktop\err.py(<span class="number">4</span>)&lt;module&gt;()</span><br><span class="line">-&gt; <span class="built_in">print</span>(<span class="number">10</span> / n)</span><br></pre></td></tr></table></figure>
<p>执行后pdb会自动指向下一行代码。特别地，任何时候我们都可以通过输入命令 <code>p 变量名</code> 来查看一个变量的值：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">(Pdb) p s</span><br><span class="line"><span class="string">&#x27;0&#x27;</span></span><br><span class="line">(Pdb) p n</span><br><span class="line"><span class="number">0</span></span><br></pre></td></tr></table></figure>
<p>继续执行：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">(Pdb) n</span><br><span class="line">ZeroDivisionError: division by zero</span><br><span class="line">&gt; c:\users\administrator\desktop\err.py(<span class="number">4</span>)&lt;module&gt;()</span><br><span class="line">-&gt; <span class="built_in">print</span>(<span class="number">10</span> / n)</span><br></pre></td></tr></table></figure>
<p>此时执行到了出错代码，pdb会报错并停止在这一行，我们可以看到它指向的地方没有发生变化。</p>
<p>输入命令 <code>q</code> 可以结束调试，退出pdb：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">(Pdb) q</span><br><span class="line"></span><br><span class="line">C:\Users\Administrator\Desktop&gt;</span><br></pre></td></tr></table></figure>
<p>这种通过pdb在命令行调试的方法在理论上是万能的，但实在是太麻烦了，打个比方，如果代码文件中有1000行代码，要运行到第999行就得敲999次命令 <code>n</code>，这样还不如执行在代码文件插入代码呢。</p>
<hr />
<h3 id="pdb.set_trace">pdb.set_trace</h3>
<p>有没有可以直接调到我们需要检查的地方再进行单步调试的调试方式呢？有的！同样是基于pdb，这次我们在代码文件中 <code>import pdb</code>，然后，在可能出错的地方插入一句 <code>pdb.set_trace()</code>，这就设置了一个断点：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># err.py</span></span><br><span class="line"><span class="keyword">import</span> pdb</span><br><span class="line"></span><br><span class="line">s = <span class="string">&#x27;0&#x27;</span></span><br><span class="line">n = <span class="built_in">int</span>(s)</span><br><span class="line">pdb.set_trace() <span class="comment"># 运行到这里会自动暂停</span></span><br><span class="line"><span class="built_in">print</span>(<span class="number">10</span> / n)</span><br></pre></td></tr></table></figure>
<p>直接运行代码，这时程序会自动<strong>在 <code>pdb.set_trace()</code> 暂停并进入pdb调试环境</strong>，可以用命令 <code>p</code> 查看变量，用命令 <code>n</code> 单步执行，或者用命令 <code>c</code> 继续运行（<strong>如果有下一个断点就会停在下一个断点，否则直接运行到程序结束</strong>）：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python err.py</span><br><span class="line">&gt; c:\users\administrator\desktop\err.py(<span class="number">7</span>)&lt;module&gt;()</span><br><span class="line">-&gt; <span class="built_in">print</span>(<span class="number">10</span> / n)</span><br><span class="line">(Pdb) p n</span><br><span class="line"><span class="number">0</span></span><br><span class="line">(Pdb) c</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">&quot;err.py&quot;</span>, line <span class="number">7</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    <span class="built_in">print</span>(<span class="number">10</span> / n)</span><br><span class="line">ZeroDivisionError: division by zero</span><br><span class="line"></span><br><span class="line">C:\Users\Administrator\Desktop&gt;</span><br></pre></td></tr></table></figure>
<p>这种方式的效率要比直接启动pdb进行单步调试更高。</p>
<hr />
<h3 id="ide">IDE</h3>
<p>除了上面介绍到的方式之外，使用IDE附带的调试功能也是很常见的。通常IDE会自带一些快捷键，允许我们方便地设置断点、单步执行、查看变量值等等。<a target="_blank" rel="noopener" href="http://www.jetbrains.com/pycharm/">PyCharm</a>是一个不错的选择。</p>
<hr />
<h3 id="小结-1">小结</h3>
<p>写程序最痛苦的事情莫过于调试，程序往往会以你意想不到的流程来运行，你期待执行的语句其实根本没有执行，这时候，就需要调试了。</p>
<p>虽然用IDE调试起来比较方便，但是最后你会发现，<code>logging</code> 才是终极武器。</p>
<hr />
<p><br></p>
<h2 id="单元测试">单元测试</h2>
<h3 id="什么是单元测试">什么是单元测试</h3>
<p>如果你听说过<strong>测试驱动开发（TDD：Test-Driven Development）</strong>，单元测试就不陌生。</p>
<p>单元测试是用来<strong>对一个模块、一个函数或者一个类来进行正确性检验的测试工作</strong>。</p>
<p>比如我们实现了一个求绝对值的函数 <code>abs()</code>，则测试用例需要包含以下这些情况：</p>
<ul>
<li>输入正数，比如1、1.2、0.99，期待返回值与输入相同；</li>
<li>输入负数，比如-1、-1.2、-0.99，期待返回值与输入相反；</li>
<li>输入0，期待返回0；</li>
<li>输入非数值类型，比如None、[]、{}，期待抛出TypeError。</li>
</ul>
<p>把上面的测试用例<strong>放到一个测试模块里</strong>，就得到了一个完整的单元测试。</p>
<p>如果单元测试通过，说明我们测试的代码能够正常工作。如果单元测试不通过，要么代码有bug，要么单元测试没有编写好，总之，需要修复代码使单元测试能够通过。</p>
<p>单元测试通过后有什么意义呢？如果我们对 <code>abs()</code> 函数代码做了修改，只需要再跑一遍单元测试，如果通过，说明我们的修改不会对 <code>abs()</code> 函数原有的行为造成影响，如果测试不通过，说明我们的修改与原有行为不一致，此时我们要么修改代码，要么修改测试。</p>
<p>这种以测试为驱动的开发模式最大的好处就是<strong>确保一个程序模块的行为符合我们设计的测试用例。在将来修改的时候，可以极大程度地保证该模块行为仍然是正确的。</strong></p>
<hr />
<h3 id="编写一个单元测试">编写一个单元测试</h3>
<p>假设我们要编写一个 <code>Dict</code> 类，这个类的行为和 <code>dict</code> 一致，但是可以通过属性来访问，可以像下面这样使用：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&gt;&gt;&gt; </span>d = <span class="type">Dict</span>(a=<span class="number">1</span>, b=<span class="number">2</span>)</span><br><span class="line"><span class="meta">&gt;&gt;&gt; </span>d[<span class="string">&#x27;a&#x27;</span>]</span><br><span class="line"><span class="number">1</span></span><br><span class="line"><span class="meta">&gt;&gt;&gt; </span>d.a</span><br><span class="line"><span class="number">1</span></span><br></pre></td></tr></table></figure>
<p>把类定义写在 <code>mydict.py</code> 文件中：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">class</span> <span class="title class_">Dict</span>(<span class="title class_ inherited__">dict</span>):</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">__init__</span>(<span class="params">self, **kw</span>):</span><br><span class="line">        <span class="built_in">super</span>().__init__(**kw)</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">__getattr__</span>(<span class="params">self, key</span>):</span><br><span class="line">        <span class="keyword">try</span>:</span><br><span class="line">            <span class="keyword">return</span> self[key]</span><br><span class="line">        <span class="keyword">except</span> KeyError:</span><br><span class="line">            <span class="keyword">raise</span> AttributeError(<span class="string">r&quot;&#x27;Dict&#x27; object has no attribute &#x27;%s&#x27;&quot;</span> % key)</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">__setattr__</span>(<span class="params">self, key, value</span>):</span><br><span class="line">        self[key] = value</span><br></pre></td></tr></table></figure>
<p>为了编写单元测试，我们需要引入Python自带的 <code>unittest</code> 模块，把单元测试写在 <code>mydict_test.py</code> 文件中：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> unittest         <span class="comment"># 导入Python自带的单元测试模块unittest</span></span><br><span class="line"><span class="keyword">from</span> mydict <span class="keyword">import</span> <span class="type">Dict</span> <span class="comment"># 导入我们要进行单元测试的模块/类/函数等等</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">class</span> <span class="title class_">TestDict</span>(unittest.TestCase):</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">test_init</span>(<span class="params">self</span>):</span><br><span class="line">        d = <span class="type">Dict</span>(a=<span class="number">1</span>, b=<span class="string">&#x27;test&#x27;</span>)</span><br><span class="line">        self.assertEqual(d.a, <span class="number">1</span>)</span><br><span class="line">        self.assertEqual(d.b, <span class="string">&#x27;test&#x27;</span>)</span><br><span class="line">        self.assertTrue(<span class="built_in">isinstance</span>(d, <span class="built_in">dict</span>))</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">test_key</span>(<span class="params">self</span>):</span><br><span class="line">        d = <span class="type">Dict</span>()</span><br><span class="line">        d[<span class="string">&#x27;key&#x27;</span>] = <span class="string">&#x27;value&#x27;</span></span><br><span class="line">        self.assertEqual(d.key, <span class="string">&#x27;value&#x27;</span>)</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">test_attr</span>(<span class="params">self</span>):</span><br><span class="line">        d = <span class="type">Dict</span>()</span><br><span class="line">        d.key = <span class="string">&#x27;value&#x27;</span></span><br><span class="line">        self.assertTrue(<span class="string">&#x27;key&#x27;</span> <span class="keyword">in</span> d)</span><br><span class="line">        self.assertEqual(d[<span class="string">&#x27;key&#x27;</span>], <span class="string">&#x27;value&#x27;</span>)</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">test_keyerror</span>(<span class="params">self</span>):</span><br><span class="line">        d = <span class="type">Dict</span>()</span><br><span class="line">        <span class="keyword">with</span> self.assertRaises(KeyError):</span><br><span class="line">            value = d[<span class="string">&#x27;empty&#x27;</span>]</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">test_attrerror</span>(<span class="params">self</span>):</span><br><span class="line">        d = <span class="type">Dict</span>()</span><br><span class="line">        <span class="keyword">with</span> self.assertRaises(AttributeError):</span><br><span class="line">            value = d.empty</span><br></pre></td></tr></table></figure>
<p>我们使用一个测试类来实现单元测试，把所有类型的测试用例都封装为该类的方法。测试类继承自 <code>unittest</code> 模块的 <code>TestCase</code> 类。注意，<strong>所有测试方法都必须以 <code>test</code> 开头</strong>，不以 <code>test</code> 开头的方法不被认为是测试方法，测试的时候不会被执行。</p>
<p>每一类测试样例都需要编写一个 <code>test_xxx()</code> 方法。由于 <code>unittest.TestCase</code> 提供了很多内置的条件判断方法，我们只需要调用这些方法就可以断言输出是否符合我们的期望。最常用的断言就是 <code>assertEqual()</code>：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">self.assertEqual(<span class="built_in">abs</span>(-<span class="number">1</span>), <span class="number">1</span>) <span class="comment"># 断言函数返回的结果与1相等</span></span><br></pre></td></tr></table></figure>
<p>另一种重要的断言就是期待抛出指定类型的Error，比如通过 <code>d['empty']</code> 访问不存在的 <code>key</code> 时，断言会抛出 <code>KeyError</code>：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">with</span> self.assertRaises(KeyError):</span><br><span class="line">    value = d[<span class="string">&#x27;empty&#x27;</span>]</span><br></pre></td></tr></table></figure>
<p>而通过 <code>d.empty</code> 访问不存在的 <code>key</code> 时，我们期待抛出 <code>AttributeError</code>：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">with</span> self.assertRaises(AttributeError):</span><br><span class="line">    value = d.empty</span><br></pre></td></tr></table></figure>
<p>当这些断言输出是否符合我们的期望时，测试用例通过，否则测试用例失败。这一小节知识说明怎样编写单元测试，具体怎么进行测试会在后续的小结中详细说明。</p>
<hr />
<h3 id="补充说明">补充说明</h3>
<p>这里补充一下 <code>with</code> 语法和 <code>assertRaises</code> 方法的说明。</p>
<h4 id="使用with的语法">使用with的语法</h4>
<p>关于 <code>with</code> 语句的相关概念可以看看<a target="_blank" rel="noopener" href="http://www.ibm.com/developerworks/cn/opensource/os-cn-pythonwith/index.html">浅谈 Python 的 with 语句</a>这篇文章。使用 <code>with</code> 的语法一般如下：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">with</span> ContextExpression [<span class="keyword">as</span> alias]:</span><br><span class="line">    <span class="keyword">with</span>-body</span><br></pre></td></tr></table></figure>
<p>例如：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">with</span> <span class="built_in">open</span>(<span class="string">r&#x27;somefileName&#x27;</span>) <span class="keyword">as</span> f:</span><br><span class="line">    <span class="keyword">for</span> line <span class="keyword">in</span> f:</span><br><span class="line">        <span class="built_in">print</span>(line)</span><br><span class="line">        <span class="comment"># ...more code</span></span><br></pre></td></tr></table></figure>
<p>跟在 <code>with</code> 关键字后的表达式称为<strong>上下文表达式</strong>，它必须能返回一个<strong>上下文管理器（Context Manager）</strong>对象。<code>with</code> 语句包裹起来的代码块则称为 <code>with</code>-语句体（with-body）。如果我们在语句体中不需要用到上下文管理器对象，就不需要为这个对象取别名（alias），也即方括号 <code>[]</code> 内的是可忽略的。比方说前面编写测试类的时候就不需要，而上面例子中由于我们需要使用文件对象中，所以取了别名 <code>f</code>。</p>
<p>上下文管理器对象都实现了 <code>__enter__()</code> 和 <code>__exit__()</code> 这两个特殊方法。执行 <code>__enter__()</code> 方法会进行<strong>运行时上下文（runtime context）</strong>，执行 <code>__exit__()</code> 方法则会退出。我们可以直接调用这两个方法来管理运行时上下文，也可以<strong>使用 <code>with</code> 语句进行管理</strong>。在执行 <code>with</code>-语句体的代码之前，<code>__enter__()</code> 方法会被自动调用，而执行完 <code>with</code>-语句体的代码之后，<code>__exit__()</code> 方法会被调用来退出运行时上下文。</p>
<h4 id="assertraises方法">assertRaises方法</h4>
<p>接下来说说 <code>assertRaises</code> 方法，它有两种使用方法：</p>
<ol type="1">
<li><code>assertRaises(exception, callable, *args, **kwds)</code></li>
<li><code>assertRaises(exception, msg=None)</code></li>
</ol>
<p>方法1测试我们使用参数 <code>*args</code> 和 <code>**kwds</code> 调用 <code>callable</code> 对象（可能是某个函数/方法）时，是否会出现 <code>exception</code> 异常，如果是则测试用例通过，否则测试失败。</p>
<p>方法2同样是测试一个异常是否出现，但当我们只传入异常时，<code>assertRaises</code> 方法会返回一个上下文管理器对象，所以我们可以用 <code>with</code> 来管理，从而实现判断运行某一段代码（放在 <code>with</code>-语句体中）时，是否出现某种异常的测试用例。</p>
<p>特别地，这些** <code>TestCase</code> 类提供的断言方法都支持传入一个关键字参数 <code>msg</code>**，我们可以使用它自定义断言失败时提示的错误信息。</p>
<p>没指定 <code>msg</code> 参数时断言失败的报错：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">AssertionError: KeyError <span class="keyword">not</span> raised</span><br></pre></td></tr></table></figure>
<p>指定了 <code>msg</code> 参数（假设指定 <code>msg = '1234'</code>）时断言失败的报错：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">AssertionError: KeyError <span class="keyword">not</span> raised : <span class="number">1234</span></span><br></pre></td></tr></table></figure>
<hr />
<h3 id="运行单元测试">运行单元测试</h3>
<p>一旦编写好单元测试，我们就可以运行单元测试，具体有两种实现方法。</p>
<p>第一次方法是直接在单元测试文件 <code>mydict_test.py</code> 的最后加上两行代码：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">if</span> __name__ == <span class="string">&#x27;__main__&#x27;</span>:</span><br><span class="line">    unittest.main()</span><br></pre></td></tr></table></figure>
<p>这样只要把 <code>mydict_test.py</code> 当成普通Python脚本来运行就可以了，运行时就会直接跑单元测试了：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python mydict_test.py</span><br><span class="line">.....</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran <span class="number">5</span> tests <span class="keyword">in</span> <span class="number">0.000</span>s</span><br><span class="line"></span><br><span class="line">OK</span><br></pre></td></tr></table></figure>
<p>第二种方法是在命令行通过参数 <code>-m unittest</code> 来运行单元测试：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python3 -m unittest mydict_test</span><br><span class="line">.....</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran <span class="number">5</span> tests <span class="keyword">in</span> <span class="number">0.000</span>s</span><br><span class="line"></span><br><span class="line">OK</span><br></pre></td></tr></table></figure>
<p>第二种方法更为推荐，因为这样可以一次批量运行多个单元测试，比方说：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python -m unittest mydict_test.py mydict_test.py</span><br><span class="line">..........</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran <span class="number">10</span> tests <span class="keyword">in</span> <span class="number">0.000</span>s</span><br><span class="line"></span><br><span class="line">OK</span><br></pre></td></tr></table></figure>
<p>此外，还有很多工具可以自动来运行这些单元测试。</p>
<p>前面都是举单元测试运行通过的例子，接下来补充一个运行不通过的例子，看看有测试用例不通过时，运行单元测试会返回什么。比方说把 <code>test_keyerror(self)</code> 方法中的 <code>value = d['empty']</code> 语句换为 <code>pass</code>，这样语句体就不会返回 <code>KeyError</code> 了，断言会失败。看看此时运行单元测试的结果：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python -m unittest mydict_test.py</span><br><span class="line">....F</span><br><span class="line">======================================================================</span><br><span class="line">FAIL: test_keyerror (mydict_test.TestDict)</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">&quot;C:\Users\Administrator\Desktop\mydict_test.py&quot;</span>, line <span class="number">27</span>, <span class="keyword">in</span> test_keyerror</span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line">AssertionError: KeyError <span class="keyword">not</span> raised</span><br><span class="line"></span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran <span class="number">5</span> tests <span class="keyword">in</span> <span class="number">0.000</span>s</span><br><span class="line"></span><br><span class="line">FAILED (failures=<span class="number">1</span>)</span><br></pre></td></tr></table></figure>
<p>可以看到这里汇报了失败的源头是 <code>test_keyerror</code> 这个测试方法，原因是这个方法的 <code>pass</code> 语句没有引起 <code>KeyError</code>，使得断言失败。最后还汇报了运行了5个测试、总共运行的时间、单元测试失败、失败的测试数为1。</p>
<h3 id="setup与teardown">setUp与tearDown</h3>
<p>在测试类中除了定义 <code>test_xxx()</code> 这样的测试方法，我们还可以编写两个特殊的 <code>setUp()</code> 和 <code>tearDown()</code> 方法。这两个方法分别<strong>在每次调用一个测试方法的前后被执行</strong>。</p>
<p>那么这两个方法有什么实际意义呢？假设测试时需要启动一个数据库，如果我们在 <code>setUp()</code> 方法中编写连接数据库的代码，在 <code>tearDown()</code> 方法中编写关闭数据库，这样我们就不必在每个测试方法中重复编写相同的代码了，也即把功能封装起来：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">class</span> <span class="title class_">TestDict</span>(unittest.TestCase):</span><br><span class="line"></span><br><span class="line">    ...</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">setUp</span>(<span class="params">self</span>):</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;setUp&#x27;</span>)</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">tearDown</span>(<span class="params">self</span>):</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;tearDown&#x27;</span>)</span><br></pre></td></tr></table></figure>
<p>再次运行单元测试：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python -m unittest mydict_test.py</span><br><span class="line">setUp</span><br><span class="line">tearDown</span><br><span class="line">.setUp</span><br><span class="line">tearDown</span><br><span class="line">.setUp</span><br><span class="line">tearDown</span><br><span class="line">.setUp</span><br><span class="line">tearDown</span><br><span class="line">.setUp</span><br><span class="line">tearDown</span><br><span class="line">.</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran <span class="number">5</span> tests <span class="keyword">in</span> <span class="number">0.016</span>s</span><br><span class="line"></span><br><span class="line">OK</span><br></pre></td></tr></table></figure>
<p>这里看到多出了一些句号 <code>.</code>，它们是每个测试方法通过之后会打印的。</p>
<hr />
<h3 id="小结-2">小结</h3>
<ul>
<li><p>单元测试可以有效地测试某个程序模块的行为，是未来重构代码的信心保证。</p></li>
<li><p>单元测试的测试用例要覆盖常用的<strong>输入组合、边界条件和异常</strong>。</p></li>
<li><p>单元测试代码要非常简单，如果测试代码太复杂，那么测试代码本身就可能有bug。</p></li>
<li><p>单元测试通过了并不意味着程序就没有bug了，但是不通过程序肯定有bug。</p></li>
<li><p>除了Python自带的 <code>unittest</code> 模块，不妨再了解一下 <a target="_blank" rel="noopener" href="https://nose.readthedocs.io/en/latest/">Nose</a> 和 <a target="_blank" rel="noopener" href="http://docs.pytest.org/en/latest/">PyTest</a> 这两个第三方模块。</p></li>
</ul>
<hr />
<p><br></p>
<h2 id="文档测试">文档测试</h2>
<h3 id="使用文档测试">使用文档测试</h3>
<p>如果你经常阅读Python的官方文档，可以看到很多官方文档都带有示例代码。比如 <a target="_blank" rel="noopener" href="https://docs.python.org/2/library/re.html"><code>re</code> 模块</a>的官方文档就带了很多示例代码，例如：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&gt;&gt;&gt; </span><span class="keyword">import</span> re</span><br><span class="line"><span class="meta">&gt;&gt;&gt; </span>m = re.search(<span class="string">&#x27;(?&lt;=abc)def&#x27;</span>, <span class="string">&#x27;abcdef&#x27;</span>)</span><br><span class="line"><span class="meta">&gt;&gt;&gt; </span>m.group(<span class="number">0</span>)</span><br><span class="line"><span class="string">&#x27;def&#x27;</span></span><br></pre></td></tr></table></figure>
<p>可以把这些示例代码在Python的交互式环境下输入并执行，结果与文档中的示例代码显示的一致。</p>
<p>这些代码与其他说明<strong>可以写在注释中，然后，由一些工具来自动生成文档</strong>。既然这些代码本身就可以复制出来直接运行，那么，<strong>可不可以自动执行写在注释中的代码</strong>呢？</p>
<p>答案是肯定的，Python内置的 <strong>“文档测试”（<code>doctest</code>）模块</strong> 可以提取出注释中的代码并执行测试。</p>
<p>当我们编写注释时，如果写上这样的注释：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">def</span> <span class="title function_">abs</span>(<span class="params">n</span>):</span><br><span class="line">    <span class="string">&#x27;&#x27;&#x27;</span></span><br><span class="line"><span class="string">    Function to get absolute value of number.</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">    Example:</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; abs(1)</span></span><br><span class="line"><span class="string">    1</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; abs(-1)</span></span><br><span class="line"><span class="string">    1</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; abs(0)</span></span><br><span class="line"><span class="string">    0</span></span><br><span class="line"><span class="string">    &#x27;&#x27;&#x27;</span></span><br><span class="line">    <span class="keyword">return</span> n <span class="keyword">if</span> n &gt;= <span class="number">0</span> <span class="keyword">else</span> (-n)</span><br></pre></td></tr></table></figure>
<p>无疑更明确地向函数的调用者说明了该函数的期望输入和输出。</p>
<p><code>doctest</code> <strong>严格按照Python交互式命令行的输入和输出来判断测试结果是否正确</strong>。只有<strong>测试异常的时候，可以用 <code>...</code> 来代替发生异常时Traceback的部分</strong>（毕竟实在是太长了..）。</p>
<p>不妨用文档测试 <code>doctest</code> 来重新实现上一节中为 <code>Dict</code> 类编写的单元测试，编写 <code>mydict.py</code> 文件：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># mydict2.py</span></span><br><span class="line"><span class="keyword">class</span> <span class="title class_">Dict</span>(<span class="title class_ inherited__">dict</span>):</span><br><span class="line">    <span class="string">&#x27;&#x27;&#x27;</span></span><br><span class="line"><span class="string">    Simple dict but also support access as x.y style.</span></span><br><span class="line"><span class="string">    # 以下为文档注释中的代码部分</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d1 = Dict()</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d1[&#x27;x&#x27;] = 100</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d1.x</span></span><br><span class="line"><span class="string">    100</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d1.y = 200</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d1[&#x27;y&#x27;]</span></span><br><span class="line"><span class="string">    200</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d2 = Dict(a=1, b=2, c=&#x27;3&#x27;)</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d2.c</span></span><br><span class="line"><span class="string">    &#x27;3&#x27;</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d2[&#x27;empty&#x27;] # 注意这里我们使用省略号...来替换了Traceback的细节</span></span><br><span class="line"><span class="string">    Traceback (most recent call last):</span></span><br><span class="line"><span class="string">        ...</span></span><br><span class="line"><span class="string">    KeyError: &#x27;empty&#x27;</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; d2.empty</span></span><br><span class="line"><span class="string">    Traceback (most recent call last):</span></span><br><span class="line"><span class="string">        ...</span></span><br><span class="line"><span class="string">    AttributeError: &#x27;Dict&#x27; object has no attribute &#x27;empty&#x27;</span></span><br><span class="line"><span class="string">    &#x27;&#x27;&#x27;</span></span><br><span class="line">    <span class="comment"># 以下为该类的方法</span></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">__init__</span>(<span class="params">self, **kw</span>):</span><br><span class="line">        <span class="built_in">super</span>(<span class="type">Dict</span>, self).__init__(**kw)</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">__getattr__</span>(<span class="params">self, key</span>):</span><br><span class="line">        <span class="keyword">try</span>:</span><br><span class="line">            <span class="keyword">return</span> self[key]</span><br><span class="line">        <span class="keyword">except</span> KeyError:</span><br><span class="line">            <span class="keyword">raise</span> AttributeError(<span class="string">r&quot;&#x27;Dict&#x27; object has no attribute &#x27;%s&#x27;&quot;</span> % key)</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">__setattr__</span>(<span class="params">self, key, value</span>):</span><br><span class="line">        self[key] = value</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__==<span class="string">&#x27;__main__&#x27;</span>:</span><br><span class="line">    <span class="keyword">import</span> doctest</span><br><span class="line">    doctest.testmod() <span class="comment"># 使用doctest模块的testmod函数来进行文档测试</span></span><br></pre></td></tr></table></figure>
<p>注意前面我们说的是<strong>注释</strong>，但这个注释并非使用 <code>#</code> 号标识的那种注释，而是文档注释，也即文档字符串。按<a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-0257/">PEP257</a>的定义：</p>
<blockquote>
<p>A docstring is a string literal that occurs as the first statement in a module, function, class, or method definition. Such a docstring becomes the <strong>doc</strong> special attribute of that object.</p>
</blockquote>
<p>所以这里 <code>Dict</code> 类的第一个字符串就是 <code>Dict</code> 类的文档注释，我们把用于文档测试的示例代码按照Python交互式命令行的输入和输出的标准来书写即可（只有测试异常时可以用 <code>...</code> 替换掉Traceback的部分）。</p>
<p>运行 <code>mydict.py</code>：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python mydict.py</span><br><span class="line"></span><br></pre></td></tr></table></figure>
<p><strong>文档测试通过时，程序不会有任何输出</strong>。接下来我们试试把 <code>__getattr__()</code> 方法注释掉（这样就不能通过把字典的key作为属性来访问了），此时再运行 <code>mydict.py</code>：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line">C:\Users\Administrator\Desktop&gt;python mydict.py</span><br><span class="line">**********************************************************************</span><br><span class="line">File <span class="string">&quot;mydict.py&quot;</span>, line <span class="number">7</span>, <span class="keyword">in</span> __main__.<span class="type">Dict</span></span><br><span class="line">Failed example:</span><br><span class="line">    d1.x</span><br><span class="line">Exception raised:</span><br><span class="line">    Traceback (most recent call last):</span><br><span class="line">      File <span class="string">&quot;F:\Anaconda3\lib\doctest.py&quot;</span>, line <span class="number">1320</span>, <span class="keyword">in</span> __run</span><br><span class="line">        compileflags, <span class="number">1</span>), test.globs)</span><br><span class="line">      File <span class="string">&quot;&lt;doctest __main__.Dict[2]&gt;&quot;</span>, line <span class="number">1</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">        d1.x</span><br><span class="line">    AttributeError: <span class="string">&#x27;Dict&#x27;</span> <span class="built_in">object</span> has no attribute <span class="string">&#x27;x&#x27;</span></span><br><span class="line">**********************************************************************</span><br><span class="line">File <span class="string">&quot;mydict.py&quot;</span>, line <span class="number">13</span>, <span class="keyword">in</span> __main__.<span class="type">Dict</span></span><br><span class="line">Failed example:</span><br><span class="line">    d2.c</span><br><span class="line">Exception raised:</span><br><span class="line">    Traceback (most recent call last):</span><br><span class="line">      File <span class="string">&quot;F:\Anaconda3\lib\doctest.py&quot;</span>, line <span class="number">1320</span>, <span class="keyword">in</span> __run</span><br><span class="line">        compileflags, <span class="number">1</span>), test.globs)</span><br><span class="line">      File <span class="string">&quot;&lt;doctest __main__.Dict[6]&gt;&quot;</span>, line <span class="number">1</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">        d2.c</span><br><span class="line">    AttributeError: <span class="string">&#x27;Dict&#x27;</span> <span class="built_in">object</span> has no attribute <span class="string">&#x27;c&#x27;</span></span><br><span class="line">**********************************************************************</span><br><span class="line"><span class="number">1</span> items had failures:</span><br><span class="line">   <span class="number">2</span> of   <span class="number">9</span> <span class="keyword">in</span> __main__.<span class="type">Dict</span></span><br><span class="line">***Test Failed*** <span class="number">2</span> failures.</span><br></pre></td></tr></table></figure>
<p>可以看到因为没有实现把key作为属性访问的功能，此时文档注释中的两个example（即 <code>d1.x</code> 和 <code>d2.c</code> 这两行输入）出错了，而文档注释中总共包含9对输入输出example。</p>
<p>注意到，我们只在 <code>if __name__=='__main__':</code> 代码块内写了执行文档测试的逻辑，也即只有在命令行中直接运行（<code>python mydict.py</code>）时会进行文档测试。而使用者使用这个类，在别的模块中导入该类（<code>from mydict import Dict</code>）时，文档测试是不会被执行的。因此，我们不必担心文档测试会在非测试环境下被执行，编写文档测试并不会影响到使用者使用该模块。</p>
<hr />
<h3 id="练习">练习</h3>
<p>对函数 <code>fact(n)</code> 编写文档测试并执行：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">def</span> <span class="title function_">fact</span>(<span class="params">n</span>):</span><br><span class="line">    <span class="string">&#x27;&#x27;&#x27;</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; fact(1)</span></span><br><span class="line"><span class="string">    1</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; fact(5)</span></span><br><span class="line"><span class="string">    120</span></span><br><span class="line"><span class="string">    &gt;&gt;&gt; fact(0)</span></span><br><span class="line"><span class="string">    Traceback (most recent call last):</span></span><br><span class="line"><span class="string">        ...</span></span><br><span class="line"><span class="string">    ValueError</span></span><br><span class="line"><span class="string">    &#x27;&#x27;&#x27;</span></span><br><span class="line">    <span class="keyword">if</span> n &lt; <span class="number">1</span>:</span><br><span class="line">        <span class="keyword">raise</span> ValueError()</span><br><span class="line">    <span class="keyword">if</span> n == <span class="number">1</span>:</span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span></span><br><span class="line">    <span class="keyword">return</span> n * fact(n - <span class="number">1</span>)</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">&#x27;__main__&#x27;</span>:</span><br><span class="line">    <span class="keyword">import</span> doctest</span><br><span class="line">    doctest.testmod()</span><br></pre></td></tr></table></figure>
<hr />
<h3 id="小结-3">小结</h3>
<p>文档测试非常有用，不但可以用来测试，还可以直接作为示例代码。通过某些文档生成工具，就可以自动把包含文档测试的注释提取出来。用户看文档的时候，同时也能看到文档测试。</p>
<hr />
<p><br></p>
</div><div class="article-licensing box"><div class="licensing-title"><p>错误、调试与测试</p><p><a href="https://hunlp.com/posts/38807.html">https://hunlp.com/posts/38807.html</a></p></div><div class="licensing-meta level is-mobile"><div class="level-left"><div class="level-item is-narrow"><div><h6>作者</h6><p>ฅ´ω`ฅ</p></div></div><div class="level-item is-narrow"><div><h6>发布于</h6><p>2017-06-23</p></div></div><div class="level-item is-narrow"><div><h6>更新于</h6><p>2021-06-08</p></div></div><div class="level-item is-narrow"><div><h6>许可协议</h6><p><a class="icons" rel="noopener" target="_blank" title="Creative Commons" href="https://creativecommons.org/"><i class="icon fab fa-creative-commons"></i></a><a class="icons" rel="noopener" target="_blank" title="Attribution" href="https://creativecommons.org/licenses/by/4.0/"><i class="icon fab fa-creative-commons-by"></i></a><a class="icons" rel="noopener" target="_blank" title="Noncommercial" href="https://creativecommons.org/licenses/by-nc/4.0/"><i class="icon fab fa-creative-commons-nc"></i></a></p></div></div></div></div></div><hr style="height:1px;margin:1rem 0"><div class="level is-mobile is-flex"><div class="article-tags is-size-7 is-uppercase"><i class="fas fa-tags has-text-grey"></i> <a class="link-muted" rel="tag" href="/tags/%E7%AC%94%E8%AE%B0/">笔记 </a></div></div><div class="bdsharebuttonbox"><a class="bds_more" href="#" data-cmd="more"></a><a class="bds_qzone" href="#" data-cmd="qzone" title="分享到QQ空间"></a><a class="bds_tsina" href="#" data-cmd="tsina" title="分享到新浪微博"></a><a class="bds_tqq" href="#" data-cmd="tqq" title="分享到腾讯微博"></a><a class="bds_renren" href="#" data-cmd="renren" title="分享到人人网"></a><a class="bds_weixin" href="#" data-cmd="weixin" title="分享到微信"></a></div><script>window._bd_share_config = { "common": { "bdSnsKey": {}, "bdText": "", "bdMini": "2", "bdPic": "", "bdStyle": "0", "bdSize": "16" }, "share": {} }; with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script></article></div><div class="card"><div class="card-content"><h3 class="menu-label has-text-centered">喜欢这篇文章？打赏一下作者吧</h3><div class="buttons is-centered"><a class="button donate" data-type="alipay"><span class="icon is-small"><i class="fab fa-alipay"></i></span><span>支付宝</span><span class="qrcode"><img src="/img/zfb.jpg" alt="支付宝"></span></a><a class="button donate" data-type="wechat"><span class="icon is-small"><i class="fab fa-weixin"></i></span><span>微信</span><span class="qrcode"><img src="/img/wx.jpg" alt="微信"></span></a></div></div></div><nav class="post-navigation mt-4 level is-mobile"><div class="level-start"><a class="article-nav-prev level level-item link-muted" href="/posts/35486.html"><i class="level-item fas fa-chevron-left"></i><span class="level-item">IO编程</span></a></div><div class="level-end"><a class="article-nav-next level level-item link-muted" href="/posts/6022.html"><span class="level-item">面向对象高级编程</span><i class="level-item fas fa-chevron-right"></i></a></div></nav><div class="card"><div class="card-content"><h3 class="title is-5">评论</h3><div class="content" id="waline-thread"></div><script src="https://cdn.jsdelivr.net/npm/@waline/client@1.5.4/dist/Waline.min.js"></script><script>Waline({
            el: '#waline-thread',
            serverURL: "https://waline-server-gilt.vercel.app",
            path: window.location.pathname,
            lang: "zh-CN",
            visitor: false,
            emoji: ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo","https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili","https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/qq"],
            dark: "auto",
            meta: ["nick","mail","link"],
            requiredMeta: [],
            login: "enable",
            
            pageSize: 10,
            
            
            math: false,
            copyright: true,
            locale: {"placeholder":"Comment here..."},
        });</script></div></div></div><div class="column column-left is-4-tablet is-4-desktop is-3-widescreen  order-1 is-sticky"><div class="card widget" id="toc" data-type="toc"><div class="card-content"><div class="menu"><h3 class="menu-label">目录</h3><ul class="menu-list"><li><a class="level is-mobile" href="#简述"><span class="level-left"><span class="level-item">1</span><span class="level-item">简述</span></span></a></li><li><a class="level is-mobile" href="#错误处理"><span class="level-left"><span class="level-item">2</span><span class="level-item">错误处理</span></span></a><ul class="menu-list"><li><a class="level is-mobile" href="#错误码"><span class="level-left"><span class="level-item">2.1</span><span class="level-item">错误码</span></span></a></li><li><a class="level is-mobile" href="#try...except...finally"><span class="level-left"><span class="level-item">2.2</span><span class="level-item">try...except...finally</span></span></a></li><li><a class="level is-mobile" href="#错误的调用链"><span class="level-left"><span class="level-item">2.3</span><span class="level-item">错误的调用链</span></span></a></li><li><a class="level is-mobile" href="#记录错误"><span class="level-left"><span class="level-item">2.4</span><span class="level-item">记录错误</span></span></a></li><li><a class="level is-mobile" href="#抛出错误"><span class="level-left"><span class="level-item">2.5</span><span class="level-item">抛出错误</span></span></a></li><li><a class="level is-mobile" href="#小结"><span class="level-left"><span class="level-item">2.6</span><span class="level-item">小结</span></span></a></li></ul></li><li><a class="level is-mobile" href="#调试"><span class="level-left"><span class="level-item">3</span><span class="level-item">调试</span></span></a><ul class="menu-list"><li><a class="level is-mobile" href="#直接打印"><span class="level-left"><span class="level-item">3.1</span><span class="level-item">直接打印</span></span></a></li><li><a class="level is-mobile" href="#断言"><span class="level-left"><span class="level-item">3.2</span><span class="level-item">断言</span></span></a></li><li><a class="level is-mobile" href="#logging"><span class="level-left"><span class="level-item">3.3</span><span class="level-item">logging</span></span></a></li><li><a class="level is-mobile" href="#pdb"><span class="level-left"><span class="level-item">3.4</span><span class="level-item">pdb</span></span></a></li><li><a class="level is-mobile" href="#pdb.set_trace"><span class="level-left"><span class="level-item">3.5</span><span class="level-item">pdb.set_trace</span></span></a></li><li><a class="level is-mobile" href="#ide"><span class="level-left"><span class="level-item">3.6</span><span class="level-item">IDE</span></span></a></li><li><a class="level is-mobile" href="#小结-1"><span class="level-left"><span class="level-item">3.7</span><span class="level-item">小结</span></span></a></li></ul></li><li><a class="level is-mobile" href="#单元测试"><span class="level-left"><span class="level-item">4</span><span class="level-item">单元测试</span></span></a><ul class="menu-list"><li><a class="level is-mobile" href="#什么是单元测试"><span class="level-left"><span class="level-item">4.1</span><span class="level-item">什么是单元测试</span></span></a></li><li><a class="level is-mobile" href="#编写一个单元测试"><span class="level-left"><span class="level-item">4.2</span><span class="level-item">编写一个单元测试</span></span></a></li><li><a class="level is-mobile" href="#补充说明"><span class="level-left"><span class="level-item">4.3</span><span class="level-item">补充说明</span></span></a><ul class="menu-list"><li><a class="level is-mobile" href="#使用with的语法"><span class="level-left"><span class="level-item">4.3.1</span><span class="level-item">使用with的语法</span></span></a></li><li><a class="level is-mobile" href="#assertraises方法"><span class="level-left"><span class="level-item">4.3.2</span><span class="level-item">assertRaises方法</span></span></a></li></ul></li><li><a class="level is-mobile" href="#运行单元测试"><span class="level-left"><span class="level-item">4.4</span><span class="level-item">运行单元测试</span></span></a></li><li><a class="level is-mobile" href="#setup与teardown"><span class="level-left"><span class="level-item">4.5</span><span class="level-item">setUp与tearDown</span></span></a></li><li><a class="level is-mobile" href="#小结-2"><span class="level-left"><span class="level-item">4.6</span><span class="level-item">小结</span></span></a></li></ul></li><li><a class="level is-mobile" href="#文档测试"><span class="level-left"><span class="level-item">5</span><span class="level-item">文档测试</span></span></a><ul class="menu-list"><li><a class="level is-mobile" href="#使用文档测试"><span class="level-left"><span class="level-item">5.1</span><span class="level-item">使用文档测试</span></span></a></li><li><a class="level is-mobile" href="#练习"><span class="level-left"><span class="level-item">5.2</span><span class="level-item">练习</span></span></a></li><li><a class="level is-mobile" href="#小结-3"><span class="level-left"><span class="level-item">5.3</span><span class="level-item">小结</span></span></a></li></ul></li></ul></div></div><style>#toc .menu-list > li > a.is-active + .menu-list { display: block; }#toc .menu-list > li > a + .menu-list { display: none; }</style><script src="/js/toc.js" defer></script></div></div><!--!--></div></div></section><footer class="footer"><div class="container"><div class="level"><div class="level-start"><a class="footer-logo is-block mb-2" href="/"><img src="/img/logo.png" alt="MCFON" height="28"></a><p class="is-size-7"><span>&copy; 2022 ฅ´ω`ฅ</span>  Powered by <a href="https://hexo.io/" target="_blank" rel="noopener">Hexo</a> &amp; <a href="https://github.com/ppoffice/hexo-theme-icarus" target="_blank" rel="noopener">Icarus</a></p></div><div class="level-end"><div class="field has-addons"><p class="control"><a class="button is-transparent is-large" target="_blank" rel="noopener" title="Creative Commons" href="https://creativecommons.org/"><i class="fab fa-creative-commons"></i></a></p><p class="control"><a class="button is-transparent is-large" target="_blank" rel="noopener" title="Attribution 4.0 International" href="https://creativecommons.org/licenses/by/4.0/"><i class="fab fa-creative-commons-by"></i></a></p><p class="control"><a class="button is-transparent is-large" target="_blank" rel="noopener" title="Download on GitHub" href="https://github.com/ppoffice/hexo-theme-icarus"><i class="fab fa-github"></i></a></p></div></div></div></div></footer><script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/min/moment-with-locales.min.js"></script><script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.4/dist/clipboard.min.js" defer></script><script>moment.locale("zh-CN");</script><script>var IcarusThemeSettings = {
            article: {
                highlight: {
                    clipboard: true,
                    fold: 'unfolded'
                }
            }
        };</script><script src="/js/column.js"></script><script src="/js/animation.js"></script><a id="back-to-top" title="回到顶端" href="javascript:;"><i class="fas fa-chevron-up"></i></a><script src="/js/back_to_top.js" defer></script><!--!--><!--!--><!--!--><script src="https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.js" defer></script><script>window.addEventListener("load", () => {
      window.cookieconsent.initialise({
        type: "info",
        theme: "edgeless",
        static: false,
        position: "bottom-left",
        content: {
          message: "此网站使用Cookie来改善您的体验。",
          dismiss: "知道了！",
          allow: "允许使用Cookie",
          deny: "拒绝",
          link: "了解更多",
          policy: "Cookie政策",
          href: "https://www.cookiesandyou.com/",
        },
        palette: {
          popup: {
            background: "#edeff5",
            text: "#838391"
          },
          button: {
            background: "#4b81e8"
          },
        },
      });
    });</script><script src="https://cdn.jsdelivr.net/npm/lightgallery@1.10.0/dist/js/lightgallery.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js" defer></script><script>window.addEventListener("load", () => {
            if (typeof $.fn.lightGallery === 'function') {
                $('.article').lightGallery({ selector: '.gallery-item' });
            }
            if (typeof $.fn.justifiedGallery === 'function') {
                if ($('.justified-gallery > p > .gallery-item').length) {
                    $('.justified-gallery > p > .gallery-item').unwrap();
                }
                $('.justified-gallery').justifiedGallery();
            }
        });</script><!--!--><!--!--><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css"><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/auto-render.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/mhchem.min.js" defer></script><script>window.addEventListener("load", function() {
            document.querySelectorAll('[role="article"] > .content').forEach(function(element) {
                renderMathInElement(element);
            });
        });</script><script type="text/x-mathjax-config">MathJax.Hub.Config({
            'HTML-CSS': {
                matchFontHeight: false
            },
            SVG: {
                matchFontHeight: false
            },
            CommonHTML: {
                matchFontHeight: false
            },
            tex2jax: {
                inlineMath: [
                    ['$','$'],
                    ['\\(','\\)']
                ]
            }
        });</script><script src="https://cdn.jsdelivr.net/npm/mathjax@2.7.9/unpacked/MathJax.js?config=TeX-MML-AM_CHTML" defer></script><!--!--><!--!--><!--!--><script src="/js/main.js" defer></script><div class="searchbox"><div class="searchbox-container"><div class="searchbox-header"><div class="searchbox-input-container"><input class="searchbox-input" type="text" placeholder="想要查找什么..."></div><a class="searchbox-close" href="javascript:;">×</a></div><div class="searchbox-body"></div></div></div><script src="/js/insight.js" defer></script><script>document.addEventListener('DOMContentLoaded', function () {
            loadInsight({"contentUrl":"/content.json"}, {"hint":"想要查找什么...","untitled":"(无标题)","posts":"文章","pages":"页面","categories":"分类","tags":"标签"});
        });</script></body></html>